# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('affiliation', models.CharField(help_text='University/Institution/Business', max_length=200)),
                ('subjects', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField()),
            ],
            options={
                'verbose_name': 'Field of Expertise',
                'verbose_name_plural': 'Fields of Expertise',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='fields',
            field=models.ManyToManyField(to='expert_search.FieldCategory'),
        ),
    ]
